### ISSUE TITLE
Add ability to auto-reload script files

### ISSUE THREAD

**Issue by timcnicholls** [stfc-aeg/odin-sequencer#2]
Add the ability for the manager to watch loaded script files and auto-reload if the file has been modified. This should be a selectable option. May be implemented using inotify or using a similar file attribute mechanism to that in the [tornado autoreload module](https://github.com/tornadoweb/tornado/blob/master/tornado/autoreload.py).

**Comment by VKTB** [comment]
@timcnicholls We need to decide whether we want to watch at a directory or file level. If we watch at a directory level, then we will receive `IN_MODIFY` events for module files that are not loaded in the manager should they get modified (maybe by accident). However, guessing by the initial comment of this issue, I assume that we shouldn't be watching and reloading/ loading module files that have not been loaded into the manager? If this is the case, then it might be better to do it at a file level by adding watchers to all the loaded module files, and reload them when the `IN_MODIFY` event occurs. What do you think?

Given that the initial comment states that auto-reload should be a selectable option, could you please confirm whether your intention is to stop watching the directories/ files if the option is unselected? I've not yet been able to stop the watcher, but I can see that there is `remove_watch` function which might help with this.

**Comment by timcnicholls** [comment]
I think the watch should be at the file level, so that new files aren't loaded automatically. You can imagine a user starting to edit a new module file for later use and leaving it in an incomplete and/or syntactically-wrong state that would throw errors in import. 

I think also, ideally we should be able to stop the watch if the option is unselected.
